# // Permissions:
# // - corehost.admin : Permet d'utiliser les commandes d'administration de CoreHost Sumo
settings:
  prefix: "&8[&eSumo&8] &7"

gameplay:
  countdown-seconds: 5
  void-level: 50
  round-time: 60
  max-draws: 3

custom-kb:
  horizontal: 0.45
  vertical: 0.36
  sprint-multiplier: 1.3
  air-multiplier: 0.8
  max-y: 0.4
  friction: 2.0

rewards:
  # --- Récompenses de base (à la manche) ---
  coins-per-round-won: 2   # Coins donnés pour CHAQUE manche gagnée.
  
  # --- Bonus de Fin de Match (si le joueur reste jusqu'au bout) ---
  match-win-bonus: 5       # Bonus supplémentaire pour avoir remporté le match entier.
  match-lose-bonus: 2      # Bonus de "consolation" pour le perdant qui n'a pas quitté.
  
  # --- Bonus Spéciaux ---
  flawless-bonus: 5        # Bonus "Parfait" (Victoire 3-0, 4-0, etc sans perdre une manche).
  forfeit-win-bonus: 8     # Bonus donné au vainqueur si l'adversaire a "ragequit".

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""

database:
  host: "127.0.0.1"
  port: 3306
  database: "corehost"
  user: "root"
  password: ""

scoreboard:
  title: "&6&lSUMO"
  ip: "&eplay.corehost.fr"
