name: CoreHostSumo
version: 1.0-SNAPSHOT
main: fr.corehost.sumo.CoreHostSumo
api-version: '1.21'
authors: [CoreHost]
description: Plugin de jeu Sumo pour CoreHost
depend: [CoreHostGame]

commands:
  sumosetup:
    description: Configuration des maps Sumo
    usage: /sumosetup <mapName> <action>
    permission: corehost.admin
  sumo:
    description: Commandes de test local Sumo
    usage: /sumo <create|join|list|leave>
    permission: corehost.admin
  corehostsumo:
    description: Commande principale de CoreHost Sumo
    permission: corehost.admin
    permission-message: §cVous n'avez pas la permission d'exécuter cette commande.

permissions:
  corehost.admin:
    description: Permet d'utiliser les commandes d'administration de CoreHost Sumo
    default: op
