# // Permissions:
# // - corehost.admin : Permet d'utiliser les commandes d'administration de CoreHost Game
settings:
  prefix: "&8[&6CoreHost&8] &7"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""

database:
  host: "127.0.0.1"
  port: 3306
  database: "corehost"
  user: "root"
  password: ""
