name: CoreHostGame
version: 1.0-SNAPSHOT
main: fr.corehost.game.CoreHostGame
api-version: 1.13
authors: [CoreHost]
description: Module de gestion des instances de jeux via AdvancedSlimePaper
softdepend: [CloudNet-Bridge]

commands:
  corehostgame:
    description: Commande principale de CoreHost Game
    permission: corehost.admin
    permission-message: §cVous n'avez pas la permission d'exécuter cette commande.

permissions:
  corehost.admin:
    description: Permet d'utiliser les commandes d'administration de CoreHost Game
    default: op
