redis:
  host: "127.0.0.1"
  port: 6379
  password: ""

settings:
  prefix: "&8[&cStaff&8] &7"

chat:
  forbidden_words:
    - "fdp"
    - "connard"
    - "salope"
    - "tg"
    - "ntm"
    - "bite"
    - "pute"
    - "enculé"
    - "ez"
  auto_mute_duration: 15 # Durée de l'auto-mute en minutes

# -----------------------------------------------------
# Permissions du plugin CoreHost-StaffMod :
# -----------------------------------------------------
# - staffmod.use         : Permet de cliquer sur le triangle pour signaler un message (default: true)
# - staffmod.mod         : Permet d'utiliser /mod et d'ouvrir le menu de modération (default: false)
# - staffmod.staffchat   : Permet de lire et écrire dans le /sc (Staff Chat) (default: false)
# - staffmod.vanish.see  : Permet de voir les joueurs en vanish (default: false)
# - staffmod.bypasschat  : Permet d'ignorer le filtrage automatique du chat (default: false)
# -----------------------------------------------------
