# Configuration de CoreHostLobby

settings:
  prefix: "&8[&6CoreHost&8] &7"
  discord-url: "https://discord.gg/aqQM4B7jxH"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""

database:
  host: "127.0.0.1"
  port: 3306
  database: "corehost"
  user: "root"
  password: ""

games:
  Sumo:
    name: "&e&lCréer un Mini-Jeu (Sumo)"
    material: "SLIME_BALL"
    slot: 11
    max-players: 2
    max-slime-instances: 10
    has-settings-menu: true
    settings-menu-class: "fr.corehost.lobby.gui.SumoSettingsMenu"
    lore:
      - ""
      - "&7Démarrez un serveur Sumo"
      - "&7pour expulser vos adversaires"
      - "&7de l'arène !"
      - ""
      - "&a► Cliquez pour héberger"
  CTF:
    name: "&c&lCréer un Mini-Jeu (CTF)"
    material: "RED_BANNER"
    slot: 15
    max-players: 20
    max-slime-instances: 3
    lore:
      - ""
      - "&7Capture the Flag !"
      - "&7Volez le drapeau adverse"
      - "&7pour gagner la partie."
      - ""
      - "&a► Cliquez pour héberger"
