name: corehost-lobby
version: '1.0-SNAPSHOT'
main: fr.corehost.lobby.CoreHostLobby
api-version: '1.21'
authors: [ CoreHost ]
description: Lobby plugin with AdvancedSlimePaper and CloudNet integration.
softdepend:
  - CloudNet-Bridge
commands:
  spawn:
    description: Téléporte au spawn du lobby.
    aliases: [hub, lobby]
    permission: corehost.command.spawn
    permission-message: §cVous n'avez pas la permission d'exécuter cette commande.
  friend:
    description: Gérer vos amis.
    usage: /<command> [args...]
    aliases: [f, ami, amis]
    permission: corehost.command.friend
    permission-message: §cVous n'avez pas la permission d'exécuter cette commande.
  premiumexception:
    description: Gérer les exceptions de pseudo premium.
    aliases: [pe]
    permission: corehost.admin
    permission-message: §cVous n'avez pas la permission d'exécuter cette commande.
  corehost:
    description: Commande principale de CoreHost Lobby
    permission: corehost.admin
    permission-message: §cVous n'avez pas la permission d'exécuter cette commande.

permissions:
  corehost.command.spawn:
    description: Permet d'utiliser la commande de spawn
    default: true
  corehost.command.friend:
    description: Permet d'utiliser les commandes d'amis
    default: true
  corehost.admin:
    description: Permet d'utiliser les commandes d'administration
    default: op
