name: corehost-lobby
version: '1.0-SNAPSHOT'
main: fr.corehost.lobby.CoreHostLobby
api-version: '1.21'
authors: [ CoreHost ]
description: Lobby plugin with AdvancedSlimePaper and CloudNet integration.
softdepend:
  - CloudNet-Bridge
commands:
  spawn:
    description: Téléporte au spawn du lobby.
    aliases: [hub, lobby]
  friend:
    description: Gérer vos amis.
    aliases: [f, ami, amis]
